name: travio
description: "Craft unforgettable adventures with Travio, the intuitive web app designed to simplify your trip planning from dream to destination."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  google_places_flutter: ^2.0.9
  http: ^1.1.0
  uuid: ^4.5.1
  easy_debounce: ^2.0.3
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  go_router: ^16.2.1
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  calendar_date_picker2: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoEmoji-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoEmoji-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoEmoji-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoEmoji-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoEmoji-Bold.ttf
          weight: 700
